# Generated by Django 4.2.5 on 2023-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="completed",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
